from django.urls import path
from apps.store.views import *

urlpatterns = [
    path("signup/", signup, name="signup"),
    path("otp-verify/", otp_verify, name="otp_verify"),
    path("signin/", signin, name="signin"),
    path("logout/", logout, name="logout"),
    path("forgot-password/", forgot_password, name="forgot_password"),
    path("forgot-password-otp-verify/", forgot_password_otp_verify, name="forgot_password_otp_verify"),
    path("", index, name="index"),
    path("products/", products, name="products"),
    path("product-detail/<uuid:product_id>/", product_detail, name="product_detail"),
    path("cart/", cart, name="cart"),
    path("add-to-cart/<uuid:product_id>/", add_to_cart, name="add_to_cart"),
    path("cart/increase/<uuid:id>/", cart_increase, name="cart_increase"),
    path("cart/decrease/<uuid:id>/", cart_decrease, name="cart_decrease"),
    path("cart/remove/<uuid:id>/", cart_remove, name="cart_remove"),
    path("blogs/", blogs, name="blogs"),
    path("blogs/<uuid:id>/", blog_detail, name="blog_detail"),
    path("about/", about, name="about"),
    path("contact/", contact, name="contact"),
    path("profile/", profile, name="profile"),
    path("update-image/", update_image,name='update_image'),
    path("address/add/", add_address, name="add_address"),
    path("address/edit/<uuid:id>/", edit_address, name="edit_address"),
    path("address/delete/<uuid:id>/", delete_address, name="delete_address"),
    path("place-order/", place_order, name="place_order"),
    path("my-orders/", my_orders, name="my_orders"),
    path("orders/<uuid:order_id>/", order_detail, name="order_detail"),
    path("order-success/<uuid:order_id>/", order_success, name="order_success"),
    path("order/<uuid:order_id>/cancel/", cancel_order, name="cancel_order"),
]