# Generated by Django 6.0 on 2026-01-30 11:38

import apps.users.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_inqueries'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='profile',
            field=models.ImageField(blank=True, default='profile_pics/default.png', null=True, upload_to=apps.users.models.profile_upload_path),
        ),
    ]
